Preset the DPI of created Bitmap instances.
barnhill/barcodelib pull request #102
Opened 2020-11-24 17:39 UTC by binki

This consolidates all constructions of Bitmap to go through a common
method, providing a place to set the resolution. See #98.

This also presets the resolution to 96DPI for the generated Bitmap to
help further isolate the library from any effects that the system DPI
might have on operation. See #100.

This PR will likely need to be rebased if #101 is accepted, just poke me.

2020-11-27 20:30 UTC, barnhill requested changes

2020-11-27 20:30 UTC, barnhill commented on BarcodeStandard/BarcodeLib.cs
> +        internal Bitmap CreateBitmap(int width, int height)
should we make this static since it doesnt require anything from this Barcode class and is used in the `Label_UPCA` method which requires the barcode to be passed in to create the fake image

2020-11-28 06:57 UTC, binki commented on BarcodeStandard/BarcodeLib.cs
> +        internal Bitmap CreateBitmap(int width, int height)
@barnhill That would be fine with the current change. I intentionally made it nonstatic so that future changes could refer to properties on the passed in `Barcode`, but until that is done there is no reason to not just let it be static. I will update this PR.

2020-11-28 23:55 UTC, barnhill commented on BarcodeStandard/BarcodeLib.cs
> +            bitmap.SetResolution(96, 96);
we can always follow this up with a configuration option for the dpi setting

2020-11-29 00:03 UTC, barnhill commented
I agree that this change should go in after https://github.com/barnhill/barcodelib/pull/101 is merged.  Ill get on testing that hopefully tonight or tomorrow after getting back home.

2020-11-29 00:03 UTC, barnhill approved these changes

2020-11-29 05:58 UTC, binki commented on BarcodeStandard/BarcodeLib.cs
> +            bitmap.SetResolution(96, 96);
Yeah, I was thinking to allow configuration later. It’s more important to get the library to ignore the system DPI in the first place since that can cause confusion. Supporting custom DPI (though it doesn’t add much benefit beyond letting the Bitmap be marked as having a certain DPI) is a new feature and can always be done later.

2020-11-29 22:10 UTC, binki commented
@barnhill looks like this still cleanly merges. The part that would have broken with #101 doesn’t exist now that it uses static methods, heh.

2020-11-30 02:40 UTC, merged