Fix checkdigit summation and calculation, cleanup
barnhill/barcodelib pull request #103
Opened 2020-11-27 19:40 UTC by barnhill

Addresses https://github.com/barnhill/barcodelib/issues/97

2020-11-28 04:36 UTC, binki requested changes
Please fix the `Convert.ToInt32()` issue and the return of `10` instead of `0` issue. With those changes, I think it’d be good! :-)

2020-11-28 04:36 UTC, binki commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +                sum += Convert.ToInt32(Raw_Data[i]) * (even ? 3 : 1);
This has the same problem as @makuep reported in #97. See [this sharplabl](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUBgZgAIBvPIiojdU8y+gNwEMwiAlJgdwH0ARJ4EyIBeIgCIADJnQExAbjr0KqTAE4AFAGEA9lAYBTMMAB0AFW0BJKMALp1HHv0EBtCQF0AlB4W4llFRo6eoYm5lY2dgDkEpFePopKAeqYRABU7Fx8Akyunj70AL54BUA) which demonstrates how `Convert.ToInt32('0') == 48` when we need to get the numeral `0`.

Instead, you can use something like [`int.Parse($"{Raw_Data[i]}")` or, as @makuep suggested, `(Raw_Data[i] - '0')`](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUBgZgAIBvPIiojdU8y+gNwEMwiAlJgdwH0ARJ4EyIBeIgCIADJnQExAbjr0KqTAE4AFAEsowAHQAFFgGcApuoAkYkhx79BAbQkBdAL5iAlO4W4llFRswiACoidRs+ASZHJyIAWiIAcgkEz296FzwXIA=). Part of me feels like `int.Parse()` is clearer/cleaner for the programmer to read, but the `digitChar - '0'` style is common enough of a pattern that people seeing it would understand what you’re going for. Also, it is more efficient than converting to string and calling a method ;-).

2020-11-28 04:36 UTC, binki commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +            return 10 - (sum % 10);
This isn’t quite right. From what I read from [the Wikipedia article](https://en.wikipedia.org/wiki/Universal_Product_Code#Check_digit_calculation), `10` is an invalid answer. The above [will return `10` as the check digit for some inputs](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUBgZgAIBvPIiojdU8y+gNwEMwiAlJgdwH0ARJ4EyIBeIgCIADJnQEA7ATEBuOvQqpMATgAUAYSYAbAMYR9AgKYBZAPZxMEnQAszhgNa8AlgHN3wLRx78ggCUQcq49AC+KlSYAGxE7lDARHpGJubWtvZOrh7evuoS7Fx8AkxB0WThqhTMrADOEAC2IkQSYTW1LERmDGZQrcCQZh2dAGZWrFp1Ca3+pYIAdAAy/Z7ADkQAtESYirMAfKLt21vuFdU1VZ2qjS2Ion4lgUwA2u4AuttEAOQSP0EiAAqIhaXr9IgAfiIxBAu1C0Ru4IGogAhMjRjUorhEZRULJQXZvlo7kQAKS7CQhTFEbERIA===). Yes, if the value of `sum` is `10`, adding `10` to that would be `20` which is equivalent to `0` modulus 10. However, if `sum` is `10`, we want our check digit to be `0`.

The way the Wikipedia article’s algorithm solves this is by just making `0` a special case. Another way to do this would be to just modulus the result again, like [`(10 - (sum % 10)) % 10`](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUBgZgAIBvPIiojdU8y+gNwEMwiAlJgdwH0ARJ4EyIBeIgCIADJnQEA7ATEBuOvQqpMATgAUAYSYAbAMYR9AgKYBZAPZxMEnQAszhgNa8AlgHN3wLRx78ggCUQcq49AC+KlSYAGxE7lDARHpGJubWtvZOrh7evuoS7Fx8AkxB0WThqhTMrADOEAC2IkQSYTW1LERmDGZQrcCQZh2dAGZWrFp1Ca3+pYIAdAAy/Z7ADkQAtESYirMAfKLt21vuFdU1VZ2qjS2Ion4lgUwA2u4AuttEAOQSP0EiAAqIhaXr9IgAfiIxBAu1C0Ru4IGogAhMjRjUorhEZRULJQXZvlo7kQAKS7CQhcmUzFEbERIA).

2020-11-28 04:50 UTC, binki commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +            return 10 - (sum % 10);
I see that `UPCA.CheckDigit()` exists and does perform the same checksum but correctly. Perhaps that could just be factored out into a UPC utility class and shared between the two implementations?

2020-11-28 04:52 UTC, binki commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +            return 10 - (sum % 10);
The one thing to watch out for if sharing code with `UPCA` is that the `UPCA` one only looks at the first 11 digits, so that would need to be generalized to support both.

2020-11-28 23:00 UTC, barnhill commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +                sum += Convert.ToInt32(Raw_Data[i]) * (even ? 3 : 1);
omg ... dumb mistake again on my part

2020-11-28 23:05 UTC, barnhill commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +                sum += Convert.ToInt32(Raw_Data[i]) * (even ? 3 : 1);
Gonna go with the char subtract method for efficiency but comment as to what we are doing there

2020-11-28 23:19 UTC, barnhill commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +            return 10 - (sum % 10);
I think Im going to keep both symbologies completely separate including their check digit calculations to keep each symbology very isolated.  I did notice that the check digit calculations exactly the same since I2of5 starts at the end of the string and UPCA starts at the beginning.

2020-11-28 23:20 UTC, barnhill commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +            return 10 - (sum % 10);
gonna check in the changes here but ill have to test later when I get home.  Doing 80 on the interstate right now in the passenger seat of course :)

2020-11-29 05:53 UTC, binki approved these changes
Looks like this addresses the original issue and the points I raised.

Note that,. even after this, the 2of5Interleaved barcode doesn’t seem to render to look like what the Wikipedia article shows for the barcode. I’m not sure Interleave2of5 actually works… But that’s for another issue(?).

2020-11-29 21:38 UTC, barnhill commented on BarcodeStandard/Symbologies/Interleaved2of5.cs
> +            return 10 - (sum % 10);
I2of5 Mod 10 barcode proof
![Capture](https://user-images.githubusercontent.com/3878158/100554231-ea0a8180-3258-11eb-8312-46a958c54038.JPG)

2020-11-29 21:40 UTC, barnhill commented
I2of5 Mod 10
![Capture](https://user-images.githubusercontent.com/3878158/100554244-0a3a4080-3259-11eb-813d-f08124822669.JPG)

I2of5
![Capture2](https://user-images.githubusercontent.com/3878158/100554273-2ccc5980-3259-11eb-8155-e7b8d19022ce.JPG)

2020-11-29 21:43 UTC, merged